# -*- coding: utf-8 -*-
"""Build bilingual SSE manuscript drafts and an AutoResearch workbench package."""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

from build_final_paper_docx import build_docx


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
FIGURE_DIR = ROOT / "paper_figures_full"
AUTO_PROJECT_ID = "sse_slow_slip_forecasting"


FIGURES = [
    (
        "Figure 1. Geometry-aware forecasting workflow and two-subfault representation.",
        "图 1. 几何感知 forecasting 工作流与两子断层表示。",
        "../paper_figures_full/fig_method_overview.png",
    ),
    (
        "Figure 2. Data contract, event window, and history-to-future split.",
        "图 2. 数据契约、事件窗口与 history-to-future 切分。",
        "../paper_figures_full/fig_data_contract_event_window.png",
    ),
    (
        "Figure 3. Baseline horizon curves for zero, mean, and persistence comparisons.",
        "图 3. zero、mean 与 persistence baseline 的 horizon 曲线。",
        "../paper_figures_full/fig_baseline_horizon_curves.png",
    ),
    (
        "Figure 4. Full-data performance summary across random and blocked splits.",
        "图 4. random 与 blocked split 上的全量性能汇总。",
        "../paper_figures_full/fig_performance_summary.png",
    ),
    (
        "Figure 5. Training curves for the full experiment matrix.",
        "图 5. 全量实验矩阵训练曲线。",
        "../paper_figures_full/fig_training_curves_combined.png",
    ),
    (
        "Figure 6. Event-level forecast montage and physical-space examples.",
        "图 6. 事件级预测拼图与物理空间示例。",
        "../paper_figures_full/fig_event_montage.png",
    ),
]


REFERENCES_BIB = r"""@article{costantino2023cascadia,
  title = {Multi-station deep learning on geodetic time series detects slow slip events in Cascadia},
  author = {Costantino, Lorenzo and others},
  journal = {Communications Earth & Environment},
  year = {2023},
  url = {https://www.nature.com/articles/s43247-023-01107-7}
}

@article{wang2024detecting,
  title = {Detecting slow slip events in the Cascadia subduction zone from GNSS time series using deep learning},
  author = {Wang, Y. and others},
  year = {2024},
  doi = {10.1007/s10291-024-01701-y}
}

@article{costantino2024denoising,
  title = {Denoising of Geodetic Time Series Using Spatiotemporal Graph Neural Networks: Application to Slow Slip Event Extraction},
  author = {Costantino, Lorenzo and others},
  year = {2024},
  archivePrefix = {arXiv},
  eprint = {2405.03320}
}

@article{tong2023alerting,
  title = {Earthquake alerting based on spatial geodetic data by spatiotemporal information transformation learning},
  author = {Tong, Xiaohua and others},
  journal = {PNAS},
  year = {2023},
  url = {https://www.pnas.org/doi/10.1073/pnas.2302275120}
}

@article{wu2022timesnet,
  title = {TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis},
  author = {Wu, Haixu and others},
  year = {2022},
  archivePrefix = {arXiv},
  eprint = {2210.02186}
}

@article{nie2022patchtst,
  title = {A Time Series is Worth 64 Words: Long-term Forecasting with Transformers},
  author = {Nie, Yuqi and others},
  year = {2022},
  archivePrefix = {arXiv},
  eprint = {2211.14730}
}

@article{liu2023itransformer,
  title = {iTransformer: Inverted Transformers Are Effective for Time Series Forecasting},
  author = {Liu, Yong and others},
  year = {2023},
  archivePrefix = {arXiv},
  eprint = {2310.06625}
}

@article{ansari2024chronos,
  title = {Chronos: Learning the Language of Time Series},
  author = {Ansari, Abdul Fatir and others},
  year = {2024},
  archivePrefix = {arXiv},
  eprint = {2403.07815}
}
"""


def figure_overview(language: str) -> str:
    lines = ["## Figure Overview" if language == "en" else "## 图件总览"]
    for caption_en, caption_zh, path in FIGURES:
        lines.append("")
        lines.append(f"![{caption_en if language == 'en' else caption_zh}]({path})")
    return "\n".join(lines)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def build_zh_draft() -> Path:
    source = read_text(DOCS / "final_paper_manuscript_zh.md")
    source = source.replace(
        "# 几何感知慢滑移未来滑移场预测：最终论文整合稿",
        "# 几何感知慢滑移未来滑移场预测：中文论文初稿",
        1,
    )
    prefix = f"""<!-- Generated by scripts/build_bilingual_paper_drafts.py on {date.today().isoformat()} -->

本文档是面向投稿前讨论的中文论文初稿。它保留当前项目已经实现并验证的章节、图件、表格和实验结论；未完成的顶刊级补充实验单独列入 `docs/top_journal_reviewer_gap_audit_zh.md`。

"""
    marker = "## 1. 引言"
    if marker in source:
        source = source.replace(marker, figure_overview("zh") + "\n\n" + marker, 1)
    else:
        source += "\n\n" + figure_overview("zh")
    target = DOCS / "submission_draft_zh.md"
    write_text(target, prefix + source)
    return target


def english_draft() -> str:
    tables = read_text(DOCS / "paper_result_tables_current.md")
    return f"""<!-- Generated by scripts/build_bilingual_paper_drafts.py on {date.today().isoformat()} -->

# Geometry-Aware Multi-Step Forecasting of Synthetic Slow Slip Evolution from Sparse Geodetic Histories

## Abstract

Slow slip events (SSEs) are transient fault-slip processes that release tectonic strain without strong seismic radiation. Their spatiotemporal evolution is relevant to fault-state monitoring, geodetic inversion, seismic-hazard background analysis, and scenario-based disaster assessment. Existing deep-learning studies on SSEs have mainly focused on event detection from GNSS time series, geodetic denoising, and alert-oriented spatial geodetic representation learning. In contrast, direct multi-step forecasting of future fault-slip fields remains less systematically evaluated.

This paper restructures an initially unsuccessful prototype into a clean future-slip forecasting loop. Given historical GNSS observations and historical fault slip, the task is to forecast the next 50 time steps of the fault-slip field. To avoid the physical inconsistency of applying a nonnegative output to per-dimension z-scored slip targets, the training target is changed to `log1p(slip / slip_scale)` and all reported metrics are computed after inverse transformation into physical slip units. The model uses a segmented residual architecture that respects the two disconnected subfaults, represented as `15x166` and `15x36` grids, rather than forcing them into a continuous `15x202` image.

On the full synthetic catalog of 6000 events, with a raw size of 74.202 GiB, the compressed training package is audited event by event and confirmed to be a lossless full-catalog representation. Full-data experiments on an Alibaba PAI-DSW A10 GPU show that the main segmented-residual model improves h50 RMSE over persistence by 97.60% on the random split and 97.50% on the blocked split, while also reducing relative error in the total-slip-moment proxy M0. The ablation matrix shows that historical slip is the dominant information source, GNSS history contributes a useful marginal constraint, GNSS-only forecasting fails under the current sparse-station setup, and the M0 auxiliary loss improves physical-scale consistency even when it does not minimize pointwise RMSE. The work should not be interpreted as real earthquake prediction or operational warning. Instead, it provides a reproducible baseline for synthetic SSE state evolution, GNSS-assisted inversion pipelines, and future physics-aware forecasting research.

**Keywords:** slow slip events; GNSS; fault-slip forecasting; geodetic deep learning; segmented residual network; synthetic catalog

{figure_overview("en")}

## 1. Introduction

Slow slip events occupy an important regime between stable creep and rapid seismic rupture. They often lack strong seismic waves but can produce measurable surface deformation over days to months and can modify the stress state of neighboring fault regions. Continuous GNSS networks have made it possible to observe such deformation with increasing temporal resolution and to infer hidden fault-slip processes through inversion or data-driven models.

Recent machine-learning work has demonstrated that SSE-related signals can be learned from geodetic time series. Multi-station neural detectors have been trained on realistic synthetic data to detect Cascadia SSEs from raw GNSS sequences. Graph and spatiotemporal denoising models have further shown that weak SSE-related displacements can be recovered from noisy geodetic observations. However, detecting whether an SSE occurred and forecasting how a fault-slip field will evolve are different problems. Detection outputs event labels, time windows, or probabilities. Forecasting must predict a future field in a physical fault coordinate system and must be evaluated in physical units.

This paper studies the latter problem. The goal is not to predict damaging earthquake occurrence or to issue operational warnings. Instead, we evaluate a more basic and falsifiable modeling layer: under a known two-subfault geometry and a controlled synthetic catalog, are historical slip and sparse GNSS histories sufficient to forecast the next 50 steps of fault-slip evolution? This framing is relevant because a practical geodetic workflow may first estimate the current slip state through inversion or data assimilation and then use that state for short-term evolution analysis.

The earlier project failed largely because the task definition and physical constraints were misaligned. It combined inversion, reconstruction, and forecasting objectives, used per-event GNSS robust scaling, and applied nonnegative outputs to z-scored slip targets. These choices obscured what was being learned and made the physical interpretation of outputs unstable. The refactored workflow therefore enforces a data contract, physical target transform, explicit baselines, small-overfit checks, full-data training, and inference reporting.

The contributions are:

1. A reproducible future-slip forecasting loop for synthetic SSE data, including full-catalog audit, baselines, small overfit, full training, physical metrics, and demo reporting.
2. A physically compatible `log1p` slip target and train-split global GNSS normalization that avoid the old z-score/softplus conflict.
3. A geometry-aware segmented residual model for two disconnected subfaults.
4. A full-data 6000-event experiment matrix showing strong gains over persistence and clearly identifying GNSS-only forecasting as infeasible in the current sparse-station setup.

## 2. Related Work

### 2.1 GNSS-Based SSE Detection

Deep-learning studies of SSEs have most often addressed detection. Multi-station convolutional and attention-based models trained on synthetic data have detected Cascadia SSEs from raw geodetic time series. Related BiLSTM and attention approaches have used signal-separation preprocessing such as vbICA before classification. These studies establish that GNSS time series can contain learnable slow-slip signatures, but their outputs are event-detection products rather than future fault-slip fields.

### 2.2 Geodetic Denoising and Graph Learning

Raw GNSS series include instrumental noise, environmental loading, seasonal terms, station artifacts, and nontectonic signals. Spatiotemporal graph networks such as SSEdenoiser combine station-network geometry and temporal dependence to recover SSE-related displacement from noisy GNSS data. Such work is highly relevant because high-quality GNSS representation is a prerequisite for inversion and forecasting. Nevertheless, denoising remains an observation-space task, not a future fault-space forecasting task.

### 2.3 Geodetic Slip Inversion

Traditional GNSS-to-slip inversion depends on dislocation Green's functions, regularization, station geometry, and prior constraints. Real slip inversion is affected by depth resolution, sparse station coverage, and multi-source data availability. The current paper does not claim to solve professional GNSS-only inversion. The included inversion demo is a ridge-regression proxy intended to show a possible data-flow interface; the main scientific contribution is future slip forecasting given a slip-state history.

### 2.4 General Time-Series Forecasting

TimesNet, PatchTST, iTransformer, Chronos, TimesFM, and related libraries provide strong reference points for long-horizon forecasting and foundation-style time-series modeling. They motivate future external baselines. The present task, however, is not an unstructured multivariate sequence problem: the 3030 slip values correspond to two known subfault grids. This motivates first evaluating a geometry-aware model before treating all dimensions as generic variables.

## 3. Data and Problem Formulation

The dataset contains 6000 synthetic slow-slip events. The raw `data/` directory is organized into 12 subdirectories and has a total size of `79,673,958,000` bytes, or `74.202 GiB`. Each event has `T=273` time steps and `3040` columns: `3030` slip dimensions and `9` GNSS dimensions. The slip dimensions correspond to two disconnected subfaults:

- segment 1: `15x166`
- segment 2: `15x36`

For efficient training and remote transfer, the raw catalog is converted into `hf_dataset_package/`, a compressed full-catalog representation of approximately `2.838 GiB`. The package contains `manifest.csv`, `manifest.jsonl`, and `events/shard_*.npz`. It is not a sample subset. A full audit reports 6000 raw events, 6000 manifest events, continuous event ids from 1 to 6000, 188 shards, 6000 raw-vs-package comparisons, and zero exact comparison failures.

The main task is:

```text
history_gnss + history_slip -> future_slip
```

The default window uses `history_steps = 60`, `forecast_horizon = 50`, `input = history_slip[0:60] + history_gnss[0:60]`, and `target = future_slip[60:110]`. Dataset records expose `history_gnss`, `history_slip`, `future_slip`, `future_gnss`, and `metadata`, but the training objective is fixed to future-slip prediction.

Two splits are used. The random split evaluates same-distribution generalization. The blocked split partitions events by event id or generation order and tests robustness to event-family or generation-order drift. The publication gate requires at least 5% h50 RMSE improvement over persistence on the random split, at least 2% improvement on the blocked split, and no unacceptable degradation of the M0 proxy.

## 4. Method

### 4.1 Slip Target Transform

Fault slip is physically nonnegative. The previous z-score target conflicted with a nonnegative output layer because many training targets became negative. The refactored target is:

```text
encoded_slip = log1p(slip / slip_scale)
physical_slip = expm1(encoded_slip) * slip_scale
```

This transform preserves nonnegativity, compresses long-tail amplitudes, and keeps a reversible path back to physical units for evaluation.

### 4.2 Global GNSS Normalization

GNSS channels are normalized with train-split global means and standard deviations. This avoids test leakage and preserves event-to-event amplitude differences. Per-event robust scaling is avoided because it can erase the physical relation between GNSS amplitude and slip scale.

### 4.3 Segmented Residual Architecture

The model reshapes the two slip segments separately and processes them with independent convolutional branches. GNSS history is encoded by a temporal encoder and broadcast into the two segment branches. The output head predicts residual changes from the last historical slip state, making persistence a natural reference point.

### 4.4 Losses and Metrics

The training loss combines encoded-space MSE with an optional M0 auxiliary loss. The M0 proxy is:

```text
M0_proxy(t) = sum_i slip_i(t)
```

Evaluation reports physical RMSE, physical R2, M0 relative absolute error, zero/mean/persistence baselines at multiple horizons, and h50 RMSE improvement over persistence.

## 5. Experiments

The baseline set includes zero, mean, and persistence. Persistence is the strongest physical baseline because it represents the assumption that the latest slip state remains unchanged. Small-overfit runs on 16-32 events verify the data contract, inverse transform, loss, checkpoint, and physical metrics before full training.

The full training configuration uses the 6000-event catalog, `segmented_residual` as the main model, `history_slip + history_gnss` as input, 50-step `future_slip` as target, 50 epochs, batch size 16, hidden channels 64, `m0_loss_weight = 0.005`, and an Alibaba PAI-DSW NVIDIA A10 GPU.

The ablation matrix includes plain, segmented, segmented-residual, no-GNSS, GNSS-only, last-slip-only, and no-M0-loss variants.

## 6. Results

### 6.1 Main Results

| Split | Model h50 RMSE | Persistence h50 RMSE | Improvement | R2 | M0 rel abs | Gate |
| --- | ---: | ---: | ---: | ---: | ---: | --- |
| random | 0.00142173 | 0.0592355 | 97.60% | 0.999408 | 0.0155652 | PASS |
| blocked | 0.00152041 | 0.0608568 | 97.50% | 0.999359 | 0.0166794 | PASS |

The main model strongly outperforms persistence on both splits. The h50 persistence baseline is poor because future active slip cannot be captured by simply freezing the last historical frame. The neural model learns both local slip distribution and total-release evolution.

### 6.2 Full Experiment Matrix

{tables}

The architecture ablation indicates that both plain and segmented models exceed persistence, but their h50 RMSE is roughly three to four times higher than the segmented-residual model. Geometry segmentation is most useful for structural generalization, while the residual formulation is the largest single contributor to predictive accuracy.

The input ablation shows that historical slip is the dominant information source. No-GNSS and last-slip-only variants are strong, but the full input remains better on the main split summary and gives more stable physical consistency. GNSS-only forecasting fails on both splits, implying that three-station GNSS history is insufficient to recover future full slip fields under the current task definition.

Removing the M0 loss improves random-split pointwise RMSE but substantially worsens M0 error, and on the blocked split it worsens both RMSE and M0 error. Therefore, the default model keeps the M0 auxiliary loss because the paper values physical-scale consistency rather than pointwise RMSE alone.

## 7. Scientific Significance and Application Boundary

Slow-slip forecasting is relevant to earthquake forecasting and early-warning research only as a state-estimation and scenario-analysis component. It should not be interpreted as direct prediction of damaging earthquake occurrence. The potential applications are: regional fault-state monitoring, seismic-hazard background analysis, chain-disaster scenario generation, GNSS inversion initialization, anomaly-window screening, and coupling with physics-based friction or dislocation models.

The current model cannot be used for operational warning, professional fault inversion, direct earthquake-time prediction, or deployment in unvalidated real-noise environments.

## 8. Limitations and Future Work

The major limitations are:

1. The catalog is synthetic; real-GNSS robustness remains unproven.
2. Historical slip is not directly observed in real applications and must be provided by inversion or assimilation.
3. The sparse GNSS station setup has not yet been stress-tested under station dropout, noise changes, or station-geometry perturbation.
4. The inversion demo is a proxy, not a scientific inversion module.
5. Current blocked splits remain inside the same synthetic catalog and do not yet prove cross-region or cross-physics generalization.
6. Predictive uncertainty is not quantified.

Future work should train a GNSS-dominant slip estimation module, inject realistic noise and missingness, evaluate cross-parameter and cross-region splits, add external time-series baselines, estimate uncertainty, and compare with real GNSS/SSE catalogs where available.

## 9. Conclusion

This work identifies and corrects the core reasons for failure in an earlier slow-slip deep-learning prototype: inconsistent target scaling, ambiguous task design, per-event GNSS normalization, and geometry-agnostic slip representation. The refactored pipeline forms a reproducible future-slip forecasting loop. Full-catalog experiments demonstrate that geometry-aware residual modeling can forecast synthetic short-term SSE slip evolution when historical slip state and sparse GNSS history are available. The results support using such models as research baselines for fault-state evolution and geodetic workflow design, while leaving real-data validation, uncertainty quantification, and physics-coupled inversion as required next steps before any operational interpretation.

## References

1. Costantino et al. Multi-station deep learning on geodetic time series detects slow slip events in Cascadia. Communications Earth & Environment, 2023.
2. Wang et al. Detecting slow slip events in the Cascadia subduction zone from GNSS time series using deep learning. 2024. DOI: 10.1007/s10291-024-01701-y.
3. Costantino et al. Denoising of Geodetic Time Series Using Spatiotemporal Graph Neural Networks: Application to Slow Slip Event Extraction. arXiv:2405.03320, 2024.
4. Tong et al. Earthquake alerting based on spatial geodetic data by spatiotemporal information transformation learning. PNAS, 2023.
5. Wu et al. TimesNet: Temporal 2D-Variation Modeling for General Time Series Analysis. arXiv:2210.02186, 2022.
6. Nie et al. A Time Series is Worth 64 Words: Long-term Forecasting with Transformers. arXiv:2211.14730, 2022.
7. Liu et al. iTransformer: Inverted Transformers Are Effective for Time Series Forecasting. arXiv:2310.06625, 2023.
8. Ansari et al. Chronos: Learning the Language of Time Series. arXiv:2403.07815, 2024.
9. Google Research. TimesFM. https://github.com/google-research/timesfm.
10. THUML. Time-Series-Library. https://github.com/thuml/Time-Series-Library.
"""


def build_en_draft() -> Path:
    target = DOCS / "submission_draft_en.md"
    write_text(target, english_draft())
    return target


def reviewer_gap_audit() -> str:
    return f"""# 顶刊审稿人视角缺口审计

日期：{date.today().isoformat()}

本文档从顶刊审稿人视角评估当前 SSE 论文初稿距离高水平投稿仍需补齐的内容。结论：当前项目已经形成可信的合成数据 forecasting 闭环和强实验结果，但若目标是顶级地学或机器学习交叉期刊，仍应把“合成场景下的可学性证明”与“真实业务可用性”严格分开。

## 总体判断

当前稿件可以支撑一篇方法与数据闭环论文的初稿，但还不足以直接投顶刊。最强证据是 6000 事件全量训练、random/blocked 双 split、14 项消融、全量数据审计和 GNSS-only 失败边界。最大短板是真实数据泛化、history slip 的可获得性、外部强 baseline、统计显著性和不确定性量化。

## Major Revision 级问题

| 审稿风险 | 为什么会被质疑 | 当前证据 | 必做补充 |
| --- | --- | --- | --- |
| 合成数据外推性不足 | 顶刊审稿人会要求证明模型不是只学会生成器规律 | 6000 synthetic catalog 和 blocked split | 增加跨生成参数、跨事件族、噪声增强、站点缺失 split |
| history slip 可获得性 | 真实 GNSS 不能直接观测完整 slip field | 本文主任务依赖 history_slip | 增加 GNSS-to-slip/state-estimation 前端或把任务明确限定为 assimilation 后预测 |
| persistence baseline 被过度击败 | 97% 提升很强，审稿人会担心任务过易、泄漏或 baseline 不够强 | raw-package 审计和 split 结果 | 加入 last-frame residual oracle、linear AR、ConvLSTM/U-Net、PatchTST/iTransformer 对照 |
| GNSS-only 失败削弱应用叙事 | 如果 GNSS-only 失败，真实业务入口必须解释清楚 | 两个 split 均 FAIL | 把 GNSS-only 改为未来工作；主张改为“given estimated slip state” |
| 缺少不确定性 | 地学预测任务需要置信区间和失败样本分析 | 当前只有点预测指标 | 增加 ensemble、MC dropout 或 quantile head，并报告 calibration |
| 物理约束仍偏弱 | M0 proxy 是 sum slip，不是真正 seismic moment | M0 auxiliary loss 有效 | 加入面积/刚度权重的 moment proxy，或说明当前仅为 proxy |
| 文献综述还偏薄 | 顶刊需要更完整的 GNSS inversion、SSE physics、forecasting baseline 对话 | 已有 10 篇核心来源 | 扩到 30-50 篇，区分 detection、denoising、inversion、data assimilation、forecasting |

## 建议的下一轮实验矩阵

| 优先级 | 实验 | 目标证据 | 投稿前必要性 |
| --- | --- | --- | --- |
| P0 | 跨生成参数 blocked split | 证明不是记忆同一生成族 | 顶刊必做 |
| P0 | 噪声/缺测 GNSS stress test | 证明 GNSS 辅助项稳定 | 顶刊必做 |
| P0 | 从反演 proxy 产生 history_slip 再 forecasting | 闭合真实业务入口 | 顶刊必做 |
| P1 | ConvLSTM / U-Net residual baseline | 防止审稿人认为 baseline 太弱 | 强烈建议 |
| P1 | PatchTST / iTransformer 多变量 baseline | 对齐时序预测社区 | 强烈建议 |
| P1 | Uncertainty ensemble | 给出置信区间与失败样本 | 强烈建议 |
| P2 | 更多真实 SSE case 后验对比 | 提升地学可信度 | 有真实数据时必做 |

## 写作层面的主要修改

1. 标题和摘要必须出现 `synthetic` 或 `controlled synthetic catalog`，避免被解读为真实地震预测。
2. 主张应写成“estimated/history slip state conditioned forecasting”，不要写成“from sparse GNSS directly forecasts fault slip”。
3. GNSS-only 失败不是负面结果，而是重要边界：它说明真实应用需要反演或同化前端。
4. 结果段需要同时报告 mean/zero/persistence 全 horizon 表，而不是只突出 h50。
5. Discussion 需要增加 failure cases、active slip mask、空间误差分布和 blocked split 的物理解释。
6. 参考文献应补齐 geodetic inversion、slow-slip physics、data assimilation 和 uncertainty forecasting。

## 当前可投稿定位

更稳妥的定位是：

> A reproducible synthetic benchmark and geometry-aware residual forecasting baseline for future slow-slip field evolution conditioned on estimated slip histories.

不建议当前直接定位为：

> A GNSS-only operational slow-slip or earthquake prediction system.

## 结论

当前成果已经足以形成完整初稿和内部预审版本；距离顶级论文最关键的下一步不是继续堆模型，而是补强泛化、真实入口、外部 baseline 和不确定性证据。
"""


def auto_ml_integration_note(auto_ml_root: Path) -> str:
    return f"""# auto_ml 科研工作台 SSE 联动记录

日期：{date.today().isoformat()}

## 当前状态

已将 SSE 项目整理为 auto_ml 可继续处理的研究工作台项目：

```text
{auto_ml_root / "projects" / AUTO_PROJECT_ID}
```

该项目包包含研究背景、文献综述源、证据表、局限性分析、中英文论文草稿、参考文献和结果表。它不包含 `data/`、`hf_dataset_package/`、DSW 输出目录或任何 HF/OpenAI token。

## 模型调用状态

当前 shell 环境未检测到 `OPENAI_API_KEY`，因此本轮不使用 OpenAI API。用户已确认可暂时使用平台中已绑定的 DeepSeek API；auto_ml 的 `ModelGateway` 中 DeepSeek provider 已配置为默认 provider，并已通过 live 连接测试。

本轮已通过 DeepSeek 生成两份辅助审阅材料：

```text
docs/deepseek_literature_and_positioning_review_zh.md
docs/deepseek_manuscript_polish_review_zh.md
```

并同步到：

```text
{auto_ml_root / "projects" / AUTO_PROJECT_ID / "reviews"}
```

后续如果需要切回 OpenAI，可配置 `OPENAI_API_KEY` 后再执行：

```powershell
cd "{auto_ml_root}"
$env:OPENAI_API_KEY="<your key>"
python -m pytest tests/test_v21_fixes.py::test_review_without_available_model_prompts_configuration -q
```

当前 DeepSeek 路径下，可在 Web UI 或 API 中对 `sse_slow_slip_forecasting` 继续执行：

1. 关键词生成；
2. 论文检索；
3. 文献综述生成；
4. manuscript-assist 逐节润色；
5. publication export。

## 反向升级建议

本轮发现 auto_ml 对“外部成熟项目导入”的支持仍不够显式。建议下一步增加一个正式导入入口：

- 输入：外部项目根目录、manuscript.md、figures 目录、result tables、references.bib；
- 输出：标准 `projects/<id>/knowledge|analysis|writing` 目录；
- 验证：导入后 `workspace`、`yanwen`、`export-publication` 均可识别已有章节，而不是强制从空白项目开始。

本轮已经用 SSE 项目包模拟了该目标结构，后续可以把生成脚本内化为 auto_ml 的正式功能。
"""


def write_auto_ml_package(auto_ml_root: Path, zh_md: Path, en_md: Path) -> Path:
    project = auto_ml_root / "projects" / AUTO_PROJECT_ID
    for rel in [
        "knowledge/llm_wiki_export",
        "planning",
        "analysis",
        "writing/figures",
        "writing/tables",
        "sources/notes",
        "exports",
    ]:
        (project / rel).mkdir(parents=True, exist_ok=True)

    project_yaml = f"""project_id: {AUTO_PROJECT_ID}
project_name: SSE Slow Slip Forecasting
topic: Geometry-aware future fault-slip forecasting for synthetic slow slip events
description: Imported from the SSE forecasting repository for literature review, manuscript polishing, reviewer-gap audit, and publication export.
template_id: generic_empirical_research
domain: seismology
product_name: 研文助手
workflow:
  - literature_review
  - paper_writing
  - reviewer_gap_audit
  - publication_export
source_project_root: {ROOT}
privacy_boundary:
  raw_data_included: false
  hf_tokens_included: false
  notes: Large/private data stay in the SSE workspace and are referenced only by audited summaries.
"""
    write_text(project / "project.yaml", project_yaml)
    write_text(project / "knowledge" / "research_context.md", read_text(ROOT / "research_notes" / "current_research_objective.md"))
    write_text(project / "knowledge" / "literature_review.md", read_text(DOCS / "literature_matrix_zh.md"))
    write_text(project / "knowledge" / "knowledge_gaps.md", reviewer_gap_audit())
    write_text(
        project / "knowledge" / "citation_map.json",
        json.dumps(
            {
                "sources": [
                    {"id": "sse-lit-1", "title": "SSE and GNSS deep learning literature matrix", "path": "knowledge/literature_review.md"},
                    {"id": "sse-exp-1", "title": "Full-data experiment result tables", "path": "writing/tables/paper_result_tables_current.md"},
                ],
                "claims": [
                    {"claim": "Main model exceeds persistence on random and blocked h50 metrics.", "evidence": "writing/tables/paper_result_tables_current.md"},
                    {"claim": "GNSS-only forecasting fails in the current sparse-station setup.", "evidence": "writing/tables/paper_result_tables_current.md"},
                ],
            },
            ensure_ascii=False,
            indent=2,
        ),
    )
    write_text(project / "planning" / "confirmed_path.yaml", "confirmed_path: future_slip_forecasting\nprimary_task: history_gnss_plus_history_slip_to_future_slip\n")
    write_text(project / "analysis" / "evidence_table.md", evidence_table())
    write_text(project / "analysis" / "limitation_analysis.md", reviewer_gap_audit())
    write_text(project / "writing" / "paper_outline.md", read_text(DOCS / "final_conference_paper_outline_zh.md"))
    write_text(project / "writing" / "manuscript.md", read_text(zh_md))
    write_text(project / "writing" / "manuscript_en.md", read_text(en_md))
    write_text(project / "writing" / "references.bib", REFERENCES_BIB)
    write_text(project / "writing" / "tables" / "paper_result_tables_current.md", read_text(DOCS / "paper_result_tables_current.md"))
    write_text(project / "sources" / "notes" / "full_dataset_package_audit.md", read_text(DOCS / "full_dataset_package_audit.md"))
    write_text(project / "sources" / "notes" / "dsw_main_training_results_zh.md", read_text(DOCS / "dsw_main_training_results_zh.md"))
    return project


def evidence_table() -> str:
    return """# Evidence Table

| Claim | Evidence | Source | Confidence |
| --- | --- | --- | --- |
| Full dataset contains 6000 raw events and 74.202 GiB of source data. | Full raw/package audit reports event count, byte size, and exact comparison failures. | `docs/full_dataset_package_audit.md` | High |
| Compressed training package is a full-catalog lossless representation, not a sample subset. | 6000 raw-vs-package comparisons with zero failures. | `docs/full_dataset_package_audit.md` | High |
| Main segmented-residual model exceeds persistence by about 97.5% at h50. | Random and blocked h50 result table. | `docs/paper_result_tables_current.md` | High |
| GNSS-only forecasting is not solved under the current sparse-station setup. | GNSS-only ablations fail both random and blocked gates. | `docs/paper_result_tables_current.md` | High |
| M0 auxiliary loss improves physical-scale consistency. | No-M0-loss run worsens M0 relative error, especially on blocked split. | `docs/paper_result_tables_current.md` | Medium-High |
| Current inversion demo is a proxy, not professional slip inversion. | Demo and usage docs explicitly label ridge-regression proxy. | `docs/model_demo_usage.md` | High |
"""


def check_outputs(auto_ml_root: Path) -> dict:
    files = {
        "zh_md": DOCS / "submission_draft_zh.md",
        "en_md": DOCS / "submission_draft_en.md",
        "zh_docx": DOCS / "submission_draft_zh.docx",
        "en_docx": DOCS / "submission_draft_en.docx",
        "reviewer_gap": DOCS / "top_journal_reviewer_gap_audit_zh.md",
        "auto_ml_note": DOCS / "auto_ml_workbench_sse_integration_zh.md",
        "auto_ml_project": auto_ml_root / "projects" / AUTO_PROJECT_ID / "project.yaml",
    }
    return {name: {"path": str(path), "exists": path.exists(), "bytes": path.stat().st_size if path.exists() and path.is_file() else None} for name, path in files.items()}


def build_all(auto_ml_root: Path) -> dict:
    zh_md = build_zh_draft()
    en_md = build_en_draft()
    write_text(DOCS / "top_journal_reviewer_gap_audit_zh.md", reviewer_gap_audit())
    project = write_auto_ml_package(auto_ml_root, zh_md, en_md)
    write_text(DOCS / "auto_ml_workbench_sse_integration_zh.md", auto_ml_integration_note(auto_ml_root))
    build_docx(zh_md, DOCS / "submission_draft_zh.docx")
    build_docx(en_md, DOCS / "submission_draft_en.docx")
    return {"auto_ml_project": str(project), "outputs": check_outputs(auto_ml_root)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--auto-ml-root", default=str(ROOT.parents[1] / "mm" / "auto_ml"))
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()
    auto_ml_root = Path(args.auto_ml_root)
    result = {"outputs": check_outputs(auto_ml_root)} if args.check_only else build_all(auto_ml_root)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
